= Pràctica servidor HTTP

:encoding: utf-8
:lang: ca
:toc: left
:!numbered:
//:teacher:

ifdef::teacher[]
== (Versió del professor):
endif::teacher[]

////
ifndef::teacher[]
.Entregar
====
*Resposta*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
*Solució*
====
endif::teacher[]
////

<<<

== Objectiu de la pràctica

En aquesta pràctica veurem com configurar les principals característiques
d'un servidor _proxy-cache_.

Veure com configurar els clients per utilitzar aquest servei, com configurar el
servidor _squid_ per fer de cau de pàgines web, i com configurar-lo per filtrar
pàgines concretes.

== Preparatius

* Utilitzarem l'entorn de xarxa de les pràctiques anteriors. Configurarem
_saruman_ com a servidor _proxy-cache_.

* Necessitarem el client _PC1_ per comprovar les configuracions que anem fent
al servei. El router _sauron_ haurà d'estar engegats per poder
connectar-nos a internet.

* Si no tenim el servei DHCP funcionant, haurem d'assignar una IP fixa a PC1
per tal que es pugui connectar a la xarxa.

* Seguint els passos de les pràctiques anteriors, totes les màquines han de
mostrar un prompt personalitzat i hi ha d'haver un usuari amb el vostre nom i
permisos per utilitzar *sudo*.

[IMPORTANT]
====
Cal que configureu el vostre terminal perquè al prompt aparegui el vostre nom i
la data ressaltats en diferents colors. *Això és imprescindible per avaluar
les captures*.
====

== Apartat 1: Instal·lació de l'_squid_ a _saruman_

L'Squid es un programari proxy que pot gestionar peticions HTTP, HTTPS i FTP
en una xarxa local.

Amb l'Squid podrem establir un servidor intermediari amb memòria cau i/o
filtrat.

L'Squid guardarà temporalment les pàgines estàtiques que es visitin, de manera
que si es tornen a visitar (pel mateix o per un altre client) no calgui anar-les
a buscar un altre cop a Internet. D'aquesta manera es redueix el temps de
càrrega de les pàgines i es redueix l'amplada de banda que s'utilitza per
accedir a Internet, que és l'habitual coll d'ampolla en una xarxa amb molts
clients.

Encara que actualment la major part de pàgines siguin dinàmiques, hi ha molts
dels recursos que inclouen (imatges, fulls d'estil, scripts) que són estàtics
i es poden guardar al cau.

Cal tenir en compte també que quan utilitzem un _cache_ per accedir a Internet,
el sevidor que fa de _cache_ fa d'intermediari de totes les connexions a
l'exterior, així que si no és prou ràpid o té una mala connectivitat, la xarxa
acabarà anant globalment més lenta.

Com a servidor _proxy_, l'Squid permet filtrar l'accés a pàgines web
determinades, a certs noms de domini, o bé a pàgines el nom de les quals
contingui algunes paraules clau. Amb això es pot evitar un munt de consum
d'amplada de banda no desitjat.

La instal·lació de l'Squid és immediata: només cal instal·lar el paquet
_squid3_.

Els fitxers principals que hem de tenir en comptes són els següents:

- `/etc/squid3/squid.conf`: el fitxer de configuració principal.
- `/var/log/squid3/access.log`: el fitxer de registre dels accesos que es
produeixin.
- `/var/spool/squid3`: el directori on es guardarà el cau.

== Apartat 2: Configuració bàsica

Hi ha algunes configuracions bàsiques que voldrem fer un cop instal·lat el
servidor:

=== Port on escolta l'Squid

El navegador web es comunica amb el proxy a través del protocol HTTP, però
habitualment s'utilitza un port diferent del 80 per aquest servei.

Configura l'squid per tal que escolti pel port 8080.

.Entregar
====
*Canvis fets a la configuració*
====

=== Espai de cau

Per defecte l'Squid utilitza com a cau la memòria del servidor. Si volem
que utilitzi espai al disc li hem d'indicar.

Fes que utilitzi fins a 1000 MB.

.Entregar
====
*Canvis fets a la configuració*
====

Per tal que generi l'estructura de directoris necessària, cal apagar
momentàniament el servei i executar l'ordre `squid3 -z -N`.

`-z` fa que es generi qualsevol part que falta en l'estructura del cau, mentre
que `-N` fa que el programa acabi després d'això, sense quedar-se treballant
com un dimoni.

.Entregar
====
*Resultat de l'execució de `squid3 -z`*
====

=== Xarxa autoritzada

Finalment, volem configurar quins clients poden utilitzar
el servidor intermediari. Per fer això utilitzarem una ACL (Access Control
List).

ACL (Access Control List) és un concepte de seguretat informàtica utilitzat per
a permetre la separació de privilegis. La separació de privilegis consisteix
en otorgar o no uns certs privilegis a un objecte (usuari, màquina...) que
està realitzant una consulta.

Totes les ACL es descriuen segons el següent format:

----
acl nom_acl tipus_acl descripció ...
----

Per exemple:

----
acl authorized_network src 172.16.2.0/8
----

Això crea una regla anomenada
*authorized_network* que defineix una xarxa d’origen de peticions
(*src 172.16.2.0/8*). Una vegada definida la regla es pot incloure en una de
les llistes d'accés, com `http_access`, permetent o prohibint la regla:

----
http_access allow authorized_network
----

Amb aquestes dues línies aconseguirem que només els clients de la nostra xarxa
puguin utilitzar el servei de proxy.

== Apartat 3: Configuració dels clients

Per tal d'utilitzar l'squid hem de configurar el navegador web.

Configura el firefox de _PC1_ per tal que utilitzi _saruman_ com a servidor
proxy.

.Entregar
====
*Configuració del firefox*
====

Comprova que pots navegar per Internet. Després, ves al servidor i comprova
al registre de l'squid que la navegació ha quedat registrada.

.Entregar
====
*Registre de l'squid on es veu la navegació del client*
====

== Apartat 4: Bloqueig de pàgines

Configura l'squid per fer que les màquines clients de la nostra xarxa no puguin
accedir a les pàgines següents:

www.facebook.com
www.twitter.com
www.youtube.com

.Entregar
====
*Configuració de l'squid*
====

.Entregar
====
*Comprovació que les pàgines han quedat bloquejades*
====

Fes que tampoc puguin entrar a pàgines les adreces de les quals continguin les
paraules: _games_, _download_ o _social_.

.Entregar
====
*Configuració de l'squid*
====

.Entregar
====
*Comprovació que les pàgines han quedat bloquejades*
====

Finalment, assegura't que les restriccions anteriors s'apliquen tant al
protocol HTTP com al protocol HTTPS.

.Entregar
====
*Configuració de l'squid*
====

.Entregar
====
*Comprovació que les pàgines han quedat bloquejades*
====

== Apartat 5: Bloqueig horari

L'squid també permet especificar si s'ha de donar o no connectivitat segons la
franja horària.

Volem permetre que els usuaris de la nostra xarxa es puguin connectar als
dominis anteriors, però només en el següent horari:

- Dissabtes i diumenges tot el dia.
- Divendres a partir de les 2 de la tarda.
- De dilluns a dijous de 2 a 4 de la tarda.

Afegeix la configuració necessària a l'squid per imposar aquest horari.

.Entregar
====
*Configuració de l'squid*
====

== Apartat 6: Forçar l'ús del proxy

Hi ha diverses maneres de forçar que els clients de la xarxa utilitzin el
proxy per navegar.

Una de les més directes és fer que l'iptables adreci tot el tràfic que vingui
directament dels clients cap al servidor proxy. Amb això aconseguim no només que
els clients hagin d'utilitzar forçosament el proxy, sinó que ho facin
automàticament encara que no ho configurin explícitament al seu navegador.

Això ho podem fer a _saruman_ afegint la següent regla d'iptables:

----
iptables -t nat -A PREROUTING -i ethX -s XARXA_LOCAL -p tcp --dport 80 -j REDIRECT --to-port PORT_SQUID
----

Aquí, cal substituir les següents expressions:

- **ethX**: s'ha de posar la interfície de xarxa de _saruman_ que estigui
connectada a la xarxa local que estem configurant.
- **XARXA_LOCAL**: l'adreça de la xarxa on són els clients.
- **PORT_SQUID**: port per on escolta l'squid.

Amb aquesta regla aconseguim que tot el tràfic que es dirigeix al port 80
des de qualsevol màquina de la xarxa local, es desviï a l'squid.

.Entregar
====
*Regla d'iptables, amb les diferents parts adaptades al nostre cas particular.*
====

.Entregar
====
*Sortida de `iptables -t nat -L` on es veuen les regles anteriors aplicades*
====

També li hem de dir a l'squid que actuï com un _transparent proxy_. Per fer
això podem afegir la paraula _transparent_ a la directiva *http_port*:

----
http_port 8080 transparent
----

Un cop aplicades les regles, comprova des de _PC1_ que pots navegar directament,
traient la configuració del proxy.

.Entregar
====
*Navegació des de PC1 sense tenir cap proxy configurat*
====

Comprova després al registre de l'squid que _PC1_ s'ha connectat realment a
través de l'squid, sense saber-ho.

.Entregar
====
*Registre de l'squid on veu la navegació de PC1*
====

Finalment, si tot funciona, recorda guardar les regles d'iptables.

.Entregar
====
*Ordre utilitzada per guardar les regles d'iptables*
====

== Apartat 7: Qüestions sobre ACL
