= Pràctica servidor FTP

:encoding: utf-8
:lang: ca
:toc: left
:!numbered:
//:teacher:

ifdef::teacher[]
== (Versió del professor):
endif::teacher[]

////
ifndef::teacher[]
.Entregar
====
*Resposta*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
*Solució*
====
endif::teacher[]
////

<<<

== Objectiu de la pràctica

En aquesta pràctica configurarem un servidor FTP. L'objectiu és tenir un
espai de només lectura on compartir documents amb accés obert, un espai propi
per a cadascun dels usuaris del sistema, i un espai compartit. També implantarem
una capa SSL per tal de transmetre la informació xifrada.

== Preparatius

* Utilitzarem l'entorn de xarxa de les pràctiques anteriors. Configurarem
_legolas_ (172.16.100.2) com a servidor FTP.

* Qualsevol màquina podrà actuar com a client del FTP. Si tenim el servei DNS
funcionant, podrem accedir-hi directament pel nom del servidor, en cas contrari
ho haurem de fer utilitzant la seva IP.

* Si no tenim el servei DHCP funcionant, haurem d'assignar una IP fixa a PC1
per tal que es pugui connectar a la xarxa.

* Seguint els passos de les pràctiques anteriors, totes les màquines han de
mostrar un prompt personalitzat i hi ha d'haver un usuari amb el vostre nom i
permisos per utilitzar *sudo*.

[IMPORTANT]
====
Cal que configureu el vostre terminal perquè al prompt aparegui el vostre nom i
la data ressaltats en diferents colors. *Això és imprescindible per avaluar
les captures*.
====

== Apartat 1: Preparació de la màquina *legolas*

Com hem fet amb les altres màquines, clonarem _legolas_ a partir de _base_, i
li configurarem la xarxa i els usuaris.

Com que _legolas_ és a la xarxa 172.16.100.0 però volem que es pugui comunicar
amb les xarxes 172.16.2.0 i 172.16.3.0, haurem d'afegir les rutes adequades,
igual que vam fer en el seu moment amb _sauron_.

.Entregar
====
*Captura del contingut del fitxer `/etc/network/interfaces` de _legolas_.*
====

.Entregar
====
*Captura de la taula d'enrutament.*
====

== Apartat 2: Instal·lador del servidor FTP a _legolas_

Utilitzarem el programa *vsFTPd* (_very secure FTP daemon_). A diferència
d'altres programes d'FTP, el _vsFTPd_ incorpora diverses característiques de
seguretat, com no permetre la connexió a l'usuari _root_, o permetre, de forma
senzilla, que un usuari no pugui navegar per tot el sistema de fitxers del
servidor.

Amb la configuració per defecte el servidor FTP ja permet l'accés a qualsevol
usuari del sistema. Per comprovar-ne el funcionament, utilitzarem una màquina
en el mateix segment de xarxa com, per exemple, _sauron_.

La instal·lació base de Debian ja inclou un client de FTP en línia d'ordres
(després ja passarem a client gràfic) que s'anomena, com és d'esperar, _ftp_.

Crea un fitxer de text al teu _home_ de _legolas_. Mira l'ajuda de l'ordre
_ftp_ i comprova que des de _sauron_ pots connectar al servei FTP de _legolas_
utilitzant el teu nom d'usuari i contrasenya. Descarrega't el fitxer que acabes
de crear.

.Entregar
====
*Captura de la transacció entre FTP entre _sauron_ i _legolas_.*
====

== Apartat 3: Configuració de l'enrutament

Voldrem que es pugui accedir a _legolas_ tant des de les altres xarxes internes
com des d'Internet (que en el nostre esquema no és més que la xarxa del propi
institut).

Per poder fer això hem de configurar els dos routers per tal que adrecin els
paquets que es dirigeixen al port 21 del router cap a _legolas_. Això ho fem
amb l'_iptables_, de forma similar a com en el seu moment vam configurar el
NAT de _sauron_.

----
iptables -t nat -A PREROUTING -p tcp --dport 21 -j DNAT --to-destination 172.16.100.2:21
dpkg-reconfigure iptables-persistent
----

A la primera línia estem indicant que volem afegir (-A) una regla relacionada
amb traducció d'adreces (-t nat). Diem que als paquets amb destí el port 21
(--dport 21) TCP (-p TCP) se'ls ha de modificar el destí (-j DNAT) i fer que
vagin a 172.16.100.2 (--to-destination 172.16.100.2).

A la segona línia reconfigurem el paquet _iptables-persistent_ per tal de
guardar els canvis de regles que hem fet de forma permanent.

Un cop fet això, ja podrem connectar al servei FTP des de l'ordinador amfitrió
i, de fet, des de qualsevol ordinador del centre.

Utilitza el client _filezilla_ per connectar al servei FTP de _legolas_.

.Entregar
====
*Captura de la transacció entre FTP entre l'ordinador amfitrió i _legolas_.*
====

Hem de configurar _saruman_ d'una forma similar a _sauron_ per tal que els
clients de les xarxes 172.16.2.0 i 172.16.3.0 puguin accedir al servidor FTP.

Recorda instal·lar el paquet _iptables-persistent_ (només l'havíem instal·lat
a _sauron_). Mira't bé l'exemple que hem fet per _sauron_ i dedueix les dues
regles que hem d'afegir a _saruman_.

.Entregar
====
*Captura de la configuració _iptables_ de _saruman_.*
====

Un cop tenim _saruman_ configurat, hauríem de poder accedir al servidor FTP des
de qualsevol ordinador de qualsevol de les tres xarxes internet.

.Entregar
====
*Captura de la connexió al servei FTP des de _PC1_.*
====

== Apartat 4: Configuració de l'accés anònim
