= Pràctica accés remot

:encoding: utf-8
:lang: ca
:toc: left
:!numbered:
//:teacher:

ifdef::teacher[]
== (Versió del professor):
endif::teacher[]

////
ifndef::teacher[]
.Entregar
====
*Resposta*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
*Solució*
====
endif::teacher[]
////

<<<

== Objectiu de la pràctica

L'objectiu de la pràctica és experimentar alguns dels sistemes de connexió
remota més comuns, tant en terminal com en mode gràfic.

== Preparatius

* Per aquesta pràctica necessitaràs les màquines virtuals `sauron` i
`saruman`, per enrutar els paquets de xarxa, `PC1`, com a client i per
establir-hi connexions gràfiques, i `legolas` com a servidor per a
connexions en mode text.

* Pots assignar una IP fixa a `PC1`, o utilitzar el servidor DHCP de `bilbo`.

* Seguint els passos de les pràctiques anteriors, totes les màquines han de
mostrar un prompt personalitzat i hi ha d'haver un usuari amb el vostre nom i
permisos per utilitzar *sudo*.

[IMPORTANT]
====
Cal que configureu el vostre terminal perquè al prompt aparegui el vostre nom i
la data ressaltats en diferents colors. *Això és imprescindible per avaluar
les captures*.
====

== Apartat 1: Telnet

Un dels primers sistemes per connectar-se remotament a un altre ordinador fou
el `telnet`.

Instal·la la part de servidor del *telnet* a *legolas*.

.Entregar
====
*Instal·lació del sevidor de `telnet`.*
====

Utilitza *PC1* per connectar-te a *legolas* via *telnet*. Utilitza les ordres
`whoami` i `hostname` abans i després de la connexió per comprovar amb quin
usuari i a quin ordinador estàs connectat en cada cas.

.Entregar
====
*Connexió entre _PC1_ i _legolas_.*
====

Una de les limitacions més importants del protocol `telnet` és que tota la
comunicació viatja sense xifrar. Això significa que és relativament fàcil
per un atacant que controli un node intermig capturar la informació de la
sessió, particularment l'usuari i contrasenya utilitzats per validar-se.

Utilitza el `tcpdump` a *saruman* per capturar un inici de sessió a través de
`telnet` entre *PC1* i *legolas*.

[NOTE]
====
`telnet` envia un paquet per cada tecla que premem, així que per capturar
l'usuari i contrasenya necessitarem consultar diversos paquets.

L'opció `-X` del `tcpdump` ens mostrarà la captura a temps real en hexadecimal
i en text.
====

.Entregar
====
*Captura de l'usuari i contrasenya utilitzats.*
====

Com s'ha pogut comprovar, l'ús de `telnet` presenta importants problemes de
seguretat, així que ha quedat relagat a usos molt concrets.

Actualment, el *telnet* s'utilitza per:

- fer diagnòstics de xarxa utilitzant protocols que treballin en text pla.
+
Connecta utilitzant `telnet` a `www.linuxquestions.org`, pel port 80, i envia
la següent petició HTTP:
+
----
GET / HTTP/1.1
Host: www.linuxquestions.org
Connection: close
----
+
[TIP]
====
Cal afegir una línia en blanc al final per indicar el final de la petició.
====
+
.Entregar
====
*Captura de part de la resposta obtinguda.*
====
+
[TIP]
====
Noteu que aquest tipus de proves només es poden fer en pàgines que no utilitzen
SSL.
====
+
[NOTE]
====
A la pràctica de correu electrònic vam fer una activitat similar per connectar
a través de `telnet` amb un servidor SMTP.
====

- alguns jocs i entreteniments.
+
.Entregar
====
*Captura d'una sessió de `telnet` contra `towel.blinkenlights.nl`.*
====
+
.Entregar
====
*Captura d'una sessió de `telnet` contra `mud.balzhur.org` pel port 5400.*
====

[NOTE]
====
Val a dir que les últimes versions de `telnet` incorporen una capa SSL, però
no s'estan utilitzant gaire perquè `SSH` permet fer el mateix que `telnet` i
moltes coses més.
====

== Apartat 2: SSH bàsic

Actualment, el protocol `SSH` és un dels més utilitzats per connexions a
terminals remots. A més de connexions xifrades, ofereix un munt de possibilitats
addicionals.

Consulta l'article a `https://en.wikipedia.org/wiki/Secure_Shell` i llegeix
les capacitats del protocol `SSH`.

.Entregar
====
*Explica _en les teves pròpies paraules_ tres de les capacitats que té `SSH`.*
====

En aquest apartat utilitzarem *PC1* com a servidor, per tal de poder provar
la connexió en mode gràfic.

Instal·la el servidor SSH (`openssh-server`) a *PC1*.

.Entregar
====
*Captura de la instal·lació.*
====

Localitza el fitxer de configuració principal del servidor i consulta el seu
manual. Completa les següents dades i respon a les preguntes:

.Entregar
====
1. Ruta del fitxer de configuració del **servidor** SSH:
2. Instrucció per visualitzar el manual d'aquest fitxer:
3. Port per defecte que utilitza el protocol `SSH`:
4. Versió del protocol que estem utilitzant:
5. Ruta del fitxer de configuració del **client** SSH:
6. Ruta del fitxer criptogràfic que identifica al servidor:
7. Ruta del fitxer on el client guarda els servidors coneguts:
8. Per defecte, ens podem connectar remotament com usuari root? Si la resposta
és sí, de quina manera?
9. Per a què serveixen les `HostKey`?
10. En què consisteix la separació de privilegis?
11. Pot connectar-se remotament un usuari que tingui una contrasenya en blanc?
12. Per defecte, podem utilitzar aplicacions gràfiques remotament?
====

Comprova que pots connectar per SSH des de *legolas* cap a *PC1*.

.Entregar
====
*Captura de la connexió de _legolas_  a _PC1_ per `SSH`.*
====

A continuació volem permetre que ens puguem connectar a *PC1* des de fora de la
LAN. Per això cal obrir el port necessari a *sauron* i dirigir-lo a *PC1*.

.Entregar
====
*Ordres necessàries per obrir el port del `SSH` a _sauron_.*
====

Estableix una connexió SSH des del teu ordinador de l'aula cap a *PC1*. Utilitza
`whoami` i `hostname` abans i després de la connexió.

.Entregar
====
*Connexió entre l'ordinador de l'aula i _PC1_*
====

Tanca la connexió anterior, i obre'n una altra que permeti l'execució
d'aplicacions gràfiques.

.Entregar
====
*Part del fitxer de configuració que permet establir connexions gràfiques.*
====

Executa el *gedit* a *PC1*, i fes que es visualitzi a l'escriptori de
l'ordinador de l'aula.

.Entregar
====
*Ordre utilitzada per establir la connexió i `gedit` executant-se remotament.*
====

Torna a fer el mateix, però fes ara que el *gedit* es vegi a l'escriptori
de *PC1*.

.Entregar
====
*Ordre utilitzada per establir la connexió i per executar el `gedit`.*
====

Per parelles, arrenqueu un ordinador en Windows i utilitzeu el programa
*putty* per establir una connexió remota a *PC1*.

.Entregar
====
*Connexió a _PC1_ des de Windows.*
====

Instal·leu el programa *xming* al Windows. Aquest programa permet visualitzar
aplicacions que s'estan executant en un servidor X Window, el sistema de
finestres del GNU/Linux.

Comproveu que ara podeu connectar-vos remotament des del Windows a *PC1*
utilitzant el *putty* i executar programes gràfics.

.Entregar
====
*Escriptori del Windows amb el `gedit` de _PC1_ executant-se.*
====

== Apartat 3: eines SSH

A més de connectar-nos remotament utilitzant una línia de comandes, el
protocol SSH admet una sèrie d'eines i extensions addicionals que ens permeten
traspassar fitxers des de la màquina servidora (a on ens hem connectat) cap a
la màquina client (des d'on ens connectem) i a l'inrevés.

En aquest apartat veurem algunes d'aquestes eines.

La primera que veurem és `scp`. Aquesta utilitat funciona de forma similar al
`cp` estàndard, amb la difèrencia que l'origen i el destí dels fitxers a
copiar poden ser a qualsevol de les dues màquines.

- Utilitza `scp` per copiar el fitxer `/etc/hosts` de *PC1* al directori
personal del teu ordinador.
+
.Entregar
====
*Instrucció utilitzada i resultat de l'operació.*
====

- Utilitza `scp` per copiar el directori `/etc/network` i tot el seu contingut,
del teu ordinador al teu _home_ de *PC1*.
+
.Entregar
====
*Instrucció utilitzada i resultat de l'operació.*
====

Una altra eina molt utilitzada per traspassar fitxers d'una banda a l'altra és
`sftp`. A diferència de `scp`, l'`sftp` obre un terminal interactiu que permet
moure'ns pels sistemes de fitxers dels dos _hosts_ i traspassar fitxers i
directoris d'una banda a l'altra.

Les ordres que acepta `sftp` són molt similars a les que ja vam veure per FTP.
Les ordres que comencen per `l` es refereixen al sistema local (des d'on ens
connectem). Per exemple, `lcd` s'utilitza per canviar el directori de treball
a l'ordinador local, mentre que `cd` s'utilitza per canviar el directori de
treball a l'ordinador remot.

- Utilitza `sftp` per baixar el teu _home_ complet des de *PC1* cap al teu
ordinador.
+
.Entregar
====
*Instrucció utilitzada i resultat de l'operació.*
====

Per comoditat, podem utilitzar un client gràfic per fer la mateixa tasca.
Internament, el client gràfic treballarà enviant les ordres de `sftp`
necessàries, però per nosaltres serà més fàcil orientar-nos en el sistema de
fitxers i no caldrà que recordem aquestes ordres.

Una bona elecció pel client gràfic és el programa `filezilla`, que ja vam
utilitzar per FTP, i que és multiplataforma.

- Repeteix l'apartat anterior utilitzant el client gràfic `filezilla`.
+
.Entregar
====
*Captura del `filezilla` després de realitzar l'operació.*
====

[TIP]
====
En Windows, un altre client gràfic molt utilitzat és el `winscp`.
====

Finalment, una última forma com podem accedir al sistema de fitxers remot és
muntar-lo directament com si es tractés d'una unitat extraïble, de manera que
tot el sistema de fitxers remot sigui accessible des d'un directori del sistema
de fitxers local.

Aquest mecanisme té l'avantatge que, un cop muntat el sistema remot, podem
treballar-hi oblidant completament que es tracta d'un ordinador remot, i
utilitzant les utilitats i eines que acosumem a utilitzar en el sistema local.
Per exemple, podríem editar una web que tenim penjada a l'ordinador remot
directament utilitzar l'entorn de desenvolupament habitual instal·lat al
nostre ordinador de treball.

Per utilitzar `sshfs` primer de tot cal instal·lar el paquet que conté el
client, que es diu justament `sshfs`.

[TIP]
====
També existeix un client SSHFS per Windows que es diu `win-sshfs`.
====

- Crea el directori `pc1` dins de `/mnt` al teu ordinador. Aquest serà el punt
de muntatge, és a dir, el directori des d'on accedirem al sistema de fitxers
remot.

La sintaxi de `sshfs` és la següent:

----
sshfs -o <opció1,opció2...> <lloc remot> <directori de muntatge>
----

Utilitzarem les següents opcions:

1. `allow_other`: permet que altres usuari a banda de root puguin utilitzar el
muntatge.
2. `default_permissions`: fa que el nucli calculi els permisos dels fitxers
remots (si no s'utilitza, els permisos es veuran estranys, perquè els
identificadors dels usuaris al sistema remot no són els mateixos que en el
sistema local).

Utilitza `sshfs` per muntar l'arrel del sistema de fitxers remot dins del
directori que hem creat abans.

.Entregar
====
*Ordre utilitzada i resultat obtingut.*
====

Per desmuntar el sistema de fitxers remots n'hi ha prou amb utilitzar `umount`
passant-li el punt de muntatge.

== Apartat 4: autenticació amb clau criptogràfica

Si volem connectar-nos remotament a un altre _host_ sovint, o bé volem
automatitzar alguna operació remota, haver d'introduir cada cop la
contrasenya és incòmode.

Una alternativa consisteix a canviar el sistema d'autenticació dels usuaris i
utilitzar una clau criptogràfica.

Si optem per aquesta opció, generarem una parella de claus pública/privada al
nostre ordinador i el client SSH les utilitzarà per validar-se contra el
servidor.

Essencialment, enviarem la clau pública al servidor i mantindrem la privada al
client. Cada cop que ens connectem, el servidor xifrarà una missatge aleatori
utiltizant la clau pública i l'enviarà al client. El client el dexifrarà
utilitzant la clau privada i el reenviarà al servidor, demostrant així que és
qui diu ser (només el posseïdor de la clau privada pot dexifrar el missatge
que s'ha xifrat amb la clau pública corresponent).

[NOTE]
====
Cal destacar aquí que el sistema de claus és diferent que el sistema de
contrasenya en el sentit que qui s'autentica és el propi _host_ i no
l'usuari, de manera que si el mateix ususari vol establir una connexió des
d'un altre ordinador que no disposi de la clau privada, no podrà autenticar-se
utilitzant aquest mecanisme.
====

En general, el sistema de claus es considera més segur que el sistema basat en
contrasenyes, perquè la mida de les claus és més gran que la de qualsevol
contrasenya, i el seu contingut és més aleatori.

Els dos sistemes es poden combinar: es pot permetre que els usuaris utilitzin
indistintament un o l'altre sistema, que alguns usuaris n'utilitzin un i
d'altres l'altre, o que només es permeti un sistema.

A més, la clau privada del client es pot guardar al disc xifrada. Això impedeix
que qualsevol persona que obtingui accés al disc del client pugui utilitzar la
clau per autenticar-se. A canvi, l'usuari haurà d'introduir una contrasenya cada
cop que vulgui utilitzar la clau privada. Aquesta contrasenya no viatjarà per
la xarxa, sinó que és la contrasenya que s'utilitzarà per recuperar la clau
privada del fitxer xifrat del disc.

- Generació de claus
- rsync (cron?)

== Apartat 5: túnels

- túnel local
- túnel invers

== Apartat 6: VNC

- Instal·lació
- test
