= Pràctica servidor DHCP

:encoding: utf-8
:lang: ca
:toc: left
:!numbered:
//:teacher:

ifdef::teacher[]
== (Versió del professor):
endif::teacher[]

////
ifndef::teacher[]
.Entregar
====
*Resposta*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
*Solució*
====
endif::teacher[]
////

<<<

== Objectiu de la pràctica

Configurar una màquina com a servidor DHCP i dues màquines com a clients del
servei.

== Preparatius

* Utilitzarem l'entorn de xarxa local creat durant la pràctica anterior.

* Concretament, hem de configurar la màquina *bilbo* com a servidor DHCP i les
màquines *PC1* i *PC2* com a clients. El router *saruman* ha d'estar engegat
per permetre la comunicació entre les màquines. El router *sauron* ha d'estar
engegat si volem que tinguin connexió externa.

* Seguint els passos de la pràctica anterior, totes les màquines han de mostrar
un prompt personalitzat i hi ha d'haver un usuari amb el vostre nom i permisos
per utilitzar *sudo*.

[IMPORTANT]
====
Cal que configureu el vostre terminal perquè al prompt aparegui el vostre nom i
la data ressaltats en diferents colors. *Això és imprescindible per avaluar
les captures*.
====

=== Interferències amb el servidor DHCP del centre

* És important garantir que el servidor DHCP que configurem no dóna servei
a la xarxa del centre, perquè podria fer interferències amb el servidor DHCP
real i provocar que la xarxa funcionés malament.

* Tal com ho tenim configurat això ja no pot passar, perquè *bilbo* només dóna
servei a la xarxa local on està connectat.

== Apartat 1: Preparació de la màquina *bilbo*

En principi *bilbo* ja està preparat després d'acabar la pràctica anterior.

Comprovem però el seu funcionament:

ifndef::teacher[]
.Entregar
====
*Captura del contingut del fitxer `/etc/network/interfaces` de _bilbo_.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
auto eth0
iface eth0 inet static
address 172.16.3.2
netmask 255.255.255.0
gateway 172.16.3.1
----
====
endif::teacher[]

ifndef::teacher[]
.Entregar
====
*Captura del resultat d'executar `traceroute 8.8.8.8` a _bilbo_.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  172.16.3.1 (172.16.3.1)  0.257 ms  0.190 ms  0.140 ms
 2  172.16.100.254 (172.16.100.254)  0.290 ms  0.263 ms  0.185 ms
 3  192.168.1.1 (192.168.1.1)  0.797 ms  1.114 ms  1.158 ms
 4  * * *
 5  * * *
 6  * * *
[...]
12  google-public-dns-a.google.com (8.8.8.8)  57.573 ms  57.297 ms  58.827 ms
----
====
endif::teacher[]

== Apartat 2: Instal·lació del servidor DHCP a *bilbo*

* Cerqueu el nom del paquet que conté el servidor DHCP a Debian i instal·leu-lo.

ifndef::teacher[]
.Entregar
====
*Captura de la comanda que instal·la el servidor DHCP.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
apt-cache search --names-only dhcp | grep server
udhcpd - Provides the busybox DHCP server implementation
dhcp-probe - network DHCP or BootP server discover
dhcpy6d - MAC address aware DHCPv6 server written in Python
isc-dhcp-client-dbg - ISC DHCP server for automatic IP address assignment (client debug)
isc-dhcp-dbg - ISC DHCP server for automatic IP address assignment (debuging symbols)
isc-dhcp-dev - API for accessing and modifying the DHCP server and client state
isc-dhcp-relay-dbg - ISC DHCP server for automatic IP address assignment (relay debug)
isc-dhcp-server - ISC DHCP server for automatic IP address assignment
isc-dhcp-server-dbg - ISC DHCP server for automatic IP address assignment (server debug)
isc-dhcp-server-ldap - DHCP server that uses LDAP as its backend
python-pydhcplib - Python DHCP client/server library
wide-dhcpv6-server - DHCPv6 server for automatic IPv6 hosts configuration

apt-get install isc-dhcp-server
----
====
endif::teacher[]

El servidor DHCP no funciona directament quan s'instal·la. Cal modificar
dos fitxers de configuració per indicar les opcions que volem.

El primer fitxer és `/etc/default/isc-dhcp-server`. Aquí cal modificar el
paràmetre `INTERFACES` per indicar que s'han de servir IP dinàmiques a
les peticions que arribin a l'única interfície de xarxa que té *bilbo*.

ifndef::teacher[]
.Entregar
====
*Captura del contingut del fitxer `/etc/default/isc-dhcp-server`.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
# Defaults for isc-dhcp-server initscript
# sourced by /etc/init.d/isc-dhcp-server
# installed at /etc/default/isc-dhcp-server by the maintainer scripts

#
# This is a POSIX shell fragment
#

# Path to dhcpd's config file (default: /etc/dhcp/dhcpd.conf).
#DHCPD_CONF=/etc/dhcp/dhcpd.conf

# Path to dhcpd's PID file (default: /var/run/dhcpd.pid).
#DHCPD_PID=/var/run/dhcpd.pid

# Additional options to start dhcpd with.
#	Don't use options -cf or -pf here; use DHCPD_CONF/ DHCPD_PID instead
#OPTIONS=""

# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#	Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACES="eth0"
----
====
endif::teacher[]

A part d'això, hem de modificar el fitxer principal de configuració del
servidor DHCP amb les opcions que volem.

* Quin és el nom de l'arxiu de configuració del servei DHCP? Quan modifiquem
l'arxiu, quina instrucció haurem d'executar per a què el servidor recarregui la
nova configuració?

ifndef::teacher[]
.Entregar
====
*Ruta completa a l'arxiu de configuració.*

*Instrucció utilitzada per reiniciar el servidor.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source]
----
/etc/dhcp/dhcpd.conf

systemctl restart isc-dhcp-server
----
====
endif::teacher[]

* Inseriu una captura del registre del sistema mostrant els missatges que
llença el servidor DHCP.

[source,bash]
----
sudo cat /var/log/syslog | grep dhcpd
----

ifndef::teacher[]
.Entregar
====
*Captura del resultat de la instrucció anterior.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source, bash]
----
Jul  8 13:41:14 bilbo dhcpd: Internet Systems Consortium DHCP Server 4.3.1
Jul  8 13:41:14 bilbo dhcpd: Copyright 2004-2014 Internet Systems Consortium.
Jul  8 13:41:14 bilbo dhcpd: All rights reserved.
Jul  8 13:41:14 bilbo dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Jul  8 13:41:14 bilbo dhcpd: Internet Systems Consortium DHCP Server 4.3.1
Jul  8 13:41:14 bilbo dhcpd: Copyright 2004-2014 Internet Systems Consortium.
Jul  8 13:41:14 bilbo dhcpd: All rights reserved.
Jul  8 13:41:14 bilbo dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Jul  8 13:41:14 bilbo dhcpd: Wrote 0 leases to leases file.
Jul  8 13:41:14 bilbo dhcpd:
Jul  8 13:41:14 bilbo dhcpd: No subnet declaration for eth0 (172.16.3.2).
Jul  8 13:41:14 bilbo dhcpd: ** Ignoring requests on eth0.  If this is not what
Jul  8 13:41:14 bilbo dhcpd:    you want, please write a subnet declaration
Jul  8 13:41:14 bilbo dhcpd:    in your dhcpd.conf file for the network segment
Jul  8 13:41:14 bilbo dhcpd:    to which interface eth0 is attached. **
Jul  8 13:41:14 bilbo dhcpd:
Jul  8 13:41:14 bilbo dhcpd:
Jul  8 13:41:14 bilbo dhcpd: Not configured to listen on any interfaces!
Jul  8 13:41:14 bilbo dhcpd:
Jul  8 13:41:14 bilbo dhcpd: If you think you have received this message due to a bug rather
Jul  8 13:41:14 bilbo dhcpd: than a configuration issue please read the section on submitting
Jul  8 13:41:14 bilbo dhcpd: bugs on either our web page at www.isc.org or in the README file
Jul  8 13:41:14 bilbo dhcpd: before submitting a bug.  These pages explain the proper
Jul  8 13:41:14 bilbo dhcpd: process and the information we find helpful for debugging..
Jul  8 13:41:14 bilbo dhcpd:
Jul  8 13:41:14 bilbo dhcpd: exiting.
Jul  8 13:41:16 bilbo isc-dhcp-server[1248]: Starting ISC DHCP server: dhcpdcheck syslog for diagnostics. ... failed!
----
====
endif::teacher[]

ifndef::teacher[]
.Entregar
====
*Explica el significat dels missatges de la captura anterior. Què estem veient?*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
El servidor DHCP no arrenca perquè no hem configurat com ha de respondre a les
peticions que li arribin per eth0.
====
endif::teacher[]

== Apartat 3: Servidor DHCP a la mateixa xarxa

Volem configurar el servidor DHCP per tal que doni IP als ordinadors de la
xarxa 172.16.3.0/24.

* El servidor DHCP proporcionarà la següent configuració a *totes* les màquines
client, independentment del seu segment de xarxa:

. Servidor DNS primari: 172.16.3.2
. Servidor DNS secundari: 172.16.3.22
. Nom de domini: cognom1-cognom2.test. Per exemple en Pere Roca Grau tindrà un
nom de domini roca-grau.test.
. Temps de concessió per defecte: una hora.
. Temps de concessió màxim: dues hores.

* Per a la xarxa 172.16.3.0/24, configurarem les següents opcions:

. EL servei DHCP repartirà adreces IP en el rang 172.16.3.100 –
172.16.3.254 (ambdues incloses).
. La porta d'enllaç serà 172.16.3.1.

[WARNING]
====
*Feu una còpia de seguretat del fitxer de configuració original abans de
modificar-lo.*
====

ifndef::teacher[]
.Entregar
====
*Arxiu de configuració complet, esborreu tots els comentaris i feu-lo llegible.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source, bash]
----
ddns-update-style none;

option domain-name "queralt-molina.test";
option domain-name-servers 172.16.3.2, 172.16.3.22;

default-lease-time 3600;
max-lease-time 7200;

authoritative;

log-facility local7;

subnet 172.16.3.0 netmask 255.255.255.0 {
  range 172.16.3.100 172.16.3.254;
  option routers 172.16.3.1;
  option broadcast-address 172.16.3.255;
}
----
====
endif::teacher[]

[WARNING]
====
*Recordeu reiniciar el servidor després de fer canvis a la seva configuració!*
====

== Apartat 4: Configuració de la màquina client PC1 (a la mateixa xarxa)

* Connectem temporalment la màquina PC1 a la xarxa 172.16.3.0/24. Això ho fem
directament des del VirtualBox, connectant la seva targeta de xarxa al
switch _intnet3_.

* Configurem la xarxa de la màquina PC1 de manera que eth0 adquireixi IP
mitjançant DHCP. Hauria d'estar així per defecte.

ifndef::teacher[]
.Entregar
====
*Mostrar configuració de xarxa de _PC1_*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
----
====
endif::teacher[]

* A *bilbo* seguiu els canvis al fitxer de registre del sistema amb `tail -f
 /var/log/syslog`.

* Forceu la renovació de l'adreça IP a PC1 amb `dhclient`, o a través
del NetworkManager.

ifndef::teacher[]
.Entregar
====
*Comanda per reiniciar el NetworkManager o comanda per demanar una nova IP
amb `dhclient`*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
dhclient -r eth0
dhclient eth0

systemctl restart network-manager
----
====
endif::teacher[]

* Observeu les noves línies que han aparegut al `syslog` de *bilbo*.

ifndef::teacher[]
.Entregar
====
*Captura de les últimes línies del `syslog` de _bilbo_.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
Jul  8 17:00:13 bilbo dhcpd: DHCPRELEASE of 172.16.3.101 from 08:00:27:24:bf:cb (PC1) via eth0 (found)
Jul  8 17:00:16 bilbo dhcpd: DHCPDISCOVER from 08:00:27:24:bf:cb via eth0
Jul  8 17:00:16 bilbo dhcpd: DHCPOFFER on 172.16.3.101 to 08:00:27:24:bf:cb (PC1) via eth0
Jul  8 17:00:16 bilbo dhcpd: DHCPREQUEST for 172.16.3.101 (172.16.3.2) from 08:00:27:24:bf:cb (PC1) via eth0
Jul  8 17:00:16 bilbo dhcpd: DHCPACK on 172.16.3.101 to 08:00:27:24:bf:cb (PC1) via eth0
----
====
endif::teacher[]

* Observeu el tràfic generat a l'apartat anterior utilitzant el
tcpdump a *bilbo*. Utilitza les opcions -n i -v al tcpdump. -n evita que
s'intentin resoldre els noms (encara no tenim el DNS funcionant), i -v fa que
es mostri la informació completa del paquet capturat.
. Feu que PC1 sol·liciti una nova concessió DHCP.
. Captureu les trames de tot el procés (DHCPDiscover, DHCPOffer, DHCPRequest,
  DHCPAck).

ifndef::teacher[]
.Entregar
====
*Captura de pantalla amb la sortida del tcpdump.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
17:04:14.166047 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 172.16.3.2 tell 172.16.3.101, length 46
17:04:14.166063 ARP, Ethernet (len 6), IPv4 (len 4), Reply 172.16.3.2 is-at 08:00:27:4a:13:c1, length 28
17:04:14.166201 IP (tos 0x0, ttl 64, id 18221, offset 0, flags [DF], proto UDP (17), length 328)
    172.16.3.101.68 > 172.16.3.2.67: BOOTP/DHCP, Request from 08:00:27:24:bf:cb, length 300, xid 0x9f36be03, Flags [none]
	  Client-IP 172.16.3.101
	  Client-Ethernet-Address 08:00:27:24:bf:cb
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Release
	    Server-ID Option 54, length 4: 172.16.3.2
	    Hostname Option 12, length 3: "PC1"
17:04:15.805306 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from 08:00:27:24:bf:cb, length 300, xid 0xac37352e, Flags [none]
	  Client-Ethernet-Address 08:00:27:24:bf:cb
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Requested-IP Option 50, length 4: 172.16.3.101
	    Hostname Option 12, length 3: "PC1"
	    Parameter-Request Option 55, length 13:
	      Subnet-Mask, BR, Time-Zone, Default-Gateway
	      Domain-Name, Domain-Name-Server, Option 119, Hostname
	      Netbios-Name-Server, Netbios-Scope, MTU, Classless-Static-Route
	      NTP
17:04:15.805472 IP (tos 0x0, ttl 64, id 15649, offset 0, flags [DF], proto ICMP (1), length 48)
    172.16.3.2 > 172.16.3.101: ICMP echo request, id 51798, seq 0, length 28
17:04:16.807151 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 333)
    172.16.3.2.67 > 172.16.3.101.68: BOOTP/DHCP, Reply, length 305, xid 0xac37352e, Flags [none]
	  Your-IP 172.16.3.101
	  Client-Ethernet-Address 08:00:27:24:bf:cb
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Offer
	    Server-ID Option 54, length 4: 172.16.3.2
	    Lease-Time Option 51, length 4: 3600
	    Subnet-Mask Option 1, length 4: 255.255.255.0
	    BR Option 28, length 4: 172.16.3.255
	    Default-Gateway Option 3, length 4: 172.16.3.1
	    Domain-Name Option 15, length 19: "queralt-molina.test"
	    Domain-Name-Server Option 6, length 8: 172.16.3.2,172.16.3.22
17:04:16.807532 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from 08:00:27:24:bf:cb, length 300, xid 0xac37352e, Flags [none]
	  Client-Ethernet-Address 08:00:27:24:bf:cb
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Request
	    Server-ID Option 54, length 4: 172.16.3.2
	    Requested-IP Option 50, length 4: 172.16.3.101
	    Hostname Option 12, length 3: "PC1"
	    Parameter-Request Option 55, length 13:
	      Subnet-Mask, BR, Time-Zone, Default-Gateway
	      Domain-Name, Domain-Name-Server, Option 119, Hostname
	      Netbios-Name-Server, Netbios-Scope, MTU, Classless-Static-Route
	      NTP
17:04:16.809563 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 333)
    172.16.3.2.67 > 172.16.3.101.68: BOOTP/DHCP, Reply, length 305, xid 0xac37352e, Flags [none]
	  Your-IP 172.16.3.101
	  Client-Ethernet-Address 08:00:27:24:bf:cb
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: ACK
	    Server-ID Option 54, length 4: 172.16.3.2
	    Lease-Time Option 51, length 4: 3600
	    Subnet-Mask Option 1, length 4: 255.255.255.0
	    BR Option 28, length 4: 172.16.3.255
	    Default-Gateway Option 3, length 4: 172.16.3.1
	    Domain-Name Option 15, length 19: "queralt-molina.test"
	    Domain-Name-Server Option 6, length 8: 172.16.3.2,172.16.3.22
17:04:20.816447 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 172.16.3.101 tell 172.16.3.2, length 28
17:04:20.816796 ARP, Ethernet (len 6), IPv4 (len 4), Reply 172.16.3.101 is-at 08:00:27:24:bf:cb, length 46
----
====
endif::teacher[]

* Des de la màquina PC1 verificar que tots els paràmetres adquirits són correctes.

ifndef::teacher[]
.Entregar
====
*Validar l'adreça ip*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
ifconfig eth0

eth0      Link encap:Ethernet  HWaddr 08:00:27:24:bf:cb
          inet addr:172.16.3.101  Bcast:172.16.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe24:bfcb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:42 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:6341 (6.1 KiB)  TX bytes:10530 (10.2 KiB)
----
====
endif::teacher[]

ifndef::teacher[]
.Entregar
====
*Validar la porta d'enllaç*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
route -n

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.16.3.1      0.0.0.0         UG    0      0        0 eth0
172.16.3.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
----
====
endif::teacher[]

ifndef::teacher[]
.Entregar
====
*Validar servidors dns*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
cat /etc/resolv.conf

domain queralt-molina.test
search queralt-molina.test
nameserver 172.16.3.2
nameserver 172.16.3.22
----
====
endif::teacher[]

* Forceu al client la renovació de l'adreça. Des del servidor, localitzeu
l'arxiu on s'emmagatzema el registre de les cessions DHCP, i trobeu el
fragment on s'ha registrat l'operació anterior. Ressalta la IP i l'hora de
cessió i l'hora de caducitat de la cessió.

ifndef::teacher[]
.Entregar
====
*Captura de la instrucció i el resultat*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
tail /var/lib/dhcp/dhcpd.leases

lease 172.16.3.101 {
  starts 5 2016/07/08 15:12:18;
  ends 5 2016/07/08 16:12:18;
  cltt 5 2016/07/08 15:12:18;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 08:00:27:24:bf:cb;
  client-hostname "PC1";
}
----
====
endif::teacher[]

[TIP]
====
*Les hores que es guarden a l'arxiu de concessions són en format GMT+0 (hora
  respecte al meridià de Greenwich) Si teniu ben configurada la zona horària,
  nosaltres estem a la zona GMT+1,  i trobareu una diferència negativa d'una
  o dues hores*.
====

* A la màquina PC1 descobriu l'adreça MAC de la targeta eth0 des de línia de
comandes.

ifndef::teacher[]
.Entregar
====
*Captura de la instrucció i el resultat*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
ifconfig eth0

eth0      Link encap:Ethernet  HWaddr 08:00:27:24:bf:cb
          inet addr:172.16.3.101  Bcast:172.16.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe24:bfcb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:42 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:6341 (6.1 KiB)  TX bytes:10530 (10.2 KiB)
----
====
endif::teacher[]

== Apartat 5: Reserva d'adreces IP

* A la màquina *bilbo* modifiqueu la configuració del servei DHCP. Volem que
les següents màquines (fícticies) de la subxarxa 172.16.3.0/24 tinguin una IP
reservada fixa:

. SERVIDOR_WEB: Té la MAC 00:0c:76:8b:c4:16. Volem que se li assigni la IP
172.16.3.5.
. La màquina SERVIDOR_WEB ha de rebre el servidor DNS 8.8.8.8 i la porta
d'enllaç 10.0.0.1.
. PC1 ha de rebre la IP 172.16.3.8.

ifndef::teacher[]
.Entregar
====
*Captura de la configuració*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
ddns-update-style none;

option domain-name "queralt-molina.test";
option domain-name-servers 172.16.3.2, 172.16.3.22;

default-lease-time 3600;
max-lease-time 7200;

authoritative;

log-facility local7;

subnet 172.16.3.0 netmask 255.255.255.0 {
  range 172.16.3.100 172.16.3.254;
  option routers 172.16.3.1;
  option broadcast-address 172.16.3.255;
}

host SERVIDOR_WEB {
  hardware ethernet 00:0C:76:8B:C4:16;
  fixed-address 172.16.3.5;
  option domain-name-servers 8.8.8.8;
  option routers 10.0.0.1;
}

host PC1 {
  hardware ethernet 08:00:27:24:BF:CB;
  fixed-address 172.16.3.8;
}
----
====
endif::teacher[]

* Reinicieu el servei DHCP a *bilbo*, i demaneu una renovació d'adreça a PC1.
Verifiqueu a PC1 que l'adreça adquirida és l'esperada.

ifndef::teacher[]
.Entregar
====
*Captura de la instrucció per validar l'adreça IP i del seu resultat.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
ifconfig eth0

eth0      Link encap:Ethernet  HWaddr 08:00:27:24:bf:cb
          inet addr:172.16.3.8  Bcast:172.16.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe24:bfcb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:128 errors:0 dropped:0 overruns:0 frame:0
          TX packets:158 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:14060 (13.7 KiB)  TX bytes:23312 (22.7 KiB)
----
====
endif::teacher[]

== Apartat 6: Grups d'adreces i clients registrats

* Assumirem ara que a la xarxa 172.16.3.0/24 es barregen màquines conegudes i
registrades (en sabem la MAC i la desem a l'arxiu de configuració) i
desconegudes (imagineu, per exemple, clients WIFI dels que no podem saber la
MAC).

* El DHCP assignarà:
. el rang 172.16.3.30 a 172.16.3.150 a les màquines registrades al DHCP.
. el rang 172.16.3.151 a 172.16.3.254 per a les màquines no registrades.

* Per a totes les màquines d'aquesta subxarxa, la porta d'enllaç és la
172.16.3.1, i els DNS són 172.16.3.2 i 127.16.3.22.

* Per facilitar la feina, només definirem 2 màquines amb adreces MAC
registrades, seran PC1 i OFICINA. Inventeu-vos la MAC d'OFICINA.

ifndef::teacher[]
.Entregar
====
*Captura de les modificacions de l'arxiu de configuració.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
ddns-update-style none;

option domain-name "queralt-molina.test";

default-lease-time 3600;
max-lease-time 7200;

authoritative;

log-facility local7;

subnet 172.16.3.0 netmask 255.255.255.0 {
  option domain-name-servers 172.16.3.2, 172.16.3.22;
  option routers 172.16.3.1;
  option broadcast-address 172.16.3.255;

  pool {
    range 172.16.3.151 172.16.3.254;
    allow unknown-clients;
  }
  pool {
    range 172.16.3.30 172.16.3.150;
    deny unknown-clients;
  }
}

host OFICINA {
  hardware ethernet 00:0C:76:8B:C4:16;
}

host PC1 {
  hardware ethernet 08:00:27:24:BF:CB;
}
----
====
endif::teacher[]

* Renoveu la IP de PC1 i verifiqueu que adquireix una IP del rang registrat.

ifndef::teacher[]
.Entregar
====
*Captura del terminal amb la renovació i la IP adquirida.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
eth0      Link encap:Ethernet  HWaddr 08:00:27:24:bf:cb
          inet addr:172.16.3.100  Bcast:172.16.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe24:bfcb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:152 errors:0 dropped:0 overruns:0 frame:0
          TX packets:194 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:18244 (17.8 KiB)  TX bytes:28628 (27.9 KiB)
----
====
endif::teacher[]

* Situeu PC2 a la mateixa xarxa i comprovem quina IP agafa. Verifiqueu que
adquireix una IP del rang *NO* registrat.

ifndef::teacher[]
.Entregar
====
*Captura del terminal amb la renovació i la IP adquirida.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
eth0      Link encap:Ethernet  HWaddr 08:00:27:9f:f4:57
          inet addr:172.16.3.151  Bcast:172.16.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe9f:f457/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1331 (1.2 KiB)  TX bytes:2827 (2.7 KiB)
----
====
endif::teacher[]

== Apartat 7: Configuració de PC1 i PC2 a una xarxa diferent

Volem ara traslladar els ordinadors PC1 i PC2 a la seva xarxa 172.16.2.0/24.
Ara, com que el servidor DHCP i els clients es troben a xarxes diferents, les
peticions de broadcast dels clients no arriben al servidor, i no obtenim cap
adreça IP.

Per a resoldre aquesta situació instal·larem al router *saruman* un DHCP relay.
Un relay s'encarrega de rebre les peticions dels clients d'una xarxa i
traspassar-les a l'altra xarxa, i de retornar després les respostes.

* Afegiu al servidor DHCP la configuració de la xarxa 172.16.2.0/24:

. EL servei DHCP repartirà adreces IP en el rang 172.16.2.100 –
172.16.2.254 (ambdues incloses).
. La porta d'enllaç serà 172.16.2.1.

* Esborra de la configuració qualsevol referència a la MAC de PC1 per evitar
conflictes.

ifndef::teacher[]
.Entregar
====
*Captura de la nova configuració.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
ddns-update-style none;

option domain-name "queralt-molina.test";
option domain-name-servers 172.16.3.2, 172.16.3.22;

default-lease-time 3600;
max-lease-time 7200;

authoritative;

log-facility local7;

subnet 172.16.3.0 netmask 255.255.255.0 {
  option routers 172.16.3.1;
  option broadcast-address 172.16.3.255;
  range 172.16.3.100 172.16.3.254;
}

subnet 172.16.2.0 netmask 255.255.255.0 {
  option routers 172.16.2.1;
  option broadcast-address 172.16.2.255;
  range 172.16.2.100 172.16.2.254;
}
----
====
endif::teacher[]

* Instal·leu a *saruman* el paquet *isc-dhcp-relay*. Contesteu a les preguntes
segons la nostra configuració de xarxa.

[TIP]
====
*El relay ha d'escoltar tant a la interfície de xarxa connectada a la xarxa
172.16.2.0/24 com a la que està connectada a la 172.16.3.0/24. Si no posem
aquesta última, no reenvia les respostes del servidor DHCP cap als clients.*
====

[TIP]
====
*Si no funciona a la primera i heu de reconfigurar el relay, utilitzeu
`dpkg-reconfigure`.*
====

ifndef::teacher[]
.Entregar
====
*Captura del fitxer `/etc/default/isc-dhcp-relay`.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
# Defaults for isc-dhcp-relay initscript
# sourced by /etc/init.d/isc-dhcp-relay
# installed at /etc/default/isc-dhcp-relay by the maintainer scripts

#
# This is a POSIX shell fragment
#

# What servers should the DHCP relay forward requests to?
SERVERS="172.16.3.2"

# On what interfaces should the DHCP relay (dhrelay) serve DHCP requests?
INTERFACES="eth1 eth2"

# Additional options that are passed to the DHCP relay daemon?
OPTIONS=""
----
====
endif::teacher[]

* Per comprovar que el relay està en funcionament, ho podem fer amb la
comanda `ps x | grep dhcrelay`.

ifndef::teacher[]
.Entregar
====
*Captura de la sortida de la comanda.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
[source,bash]
----
481 ?        Ss     0:00 /usr/sbin/dhcrelay -q -i eth1 -i eth2 172.16.3.2
840 tty1     S+     0:00 grep dhcrelay
----
====
endif::teacher[]

* Finalment, connecta PC1 i PC2 al switch intnet2 i comprova que agafen una
IP adequada a la seva xarxa.

ifndef::teacher[]
.Entregar
====
*Comprovació de la IP de PC1 i PC2.*
====
endif::teacher[]
ifdef::teacher[]
.Solució
====
A PC1 obtenim:
[source]
----
eth0      Link encap:Ethernet  HWaddr 08:00:27:24:bf:cb
          inet addr:172.16.2.100  Bcast:172.16.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe24:bfcb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:20 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2668 (2.6 KiB)  TX bytes:2278 (2.2 KiB)
----
I a PC2:
[source]
----
eth0      Link encap:Ethernet  HWaddr 08:00:27:9f:f4:57
          inet addr:172.16.2.101  Bcast:172.16.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe9f:f457/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:30 errors:0 dropped:0 overruns:0 frame:0
          TX packets:37 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3467 (3.3 KiB)  TX bytes:3334 (3.2 KiB)
----
====
endif::teacher[]
