= Instal·lacio i configuració del VirtualBox en Debian Jessie
:doctype: article
:encoding: utf-8
:lang: ca
:toc: left
:toclevels: 3
:numbered:
:teacher:

== Activació de la virtualització per maquinari

- Arrencar l'ordinador i entrar al _setup_ de la _BIOS_.
- Cercar una opció anomenada "Virtualization Technology" o similar, i
assegurar-se que està "enabled".
- Cercar una opció anomenada "Intel VTd" o "AMD IOMMU", i assegurar-se que
està "enabled".
- Guardar els canvis.
- Per comprovar que realment s'han habilitat, dins del Debian executar l'ordre:

[source,bash]
----
$ cat /proc/cpuinfo | grep "vmx\|svm"
----

Si l'ordre produeix alguna sortida, significa que l'acceleració per maquinari
està habilitada.

== Configuració de Debian Backports

El VirtualBox es troba als dipòsits de paquets de Debian. És probable que la
versió disponible a la distribució estable de Debian sigui una mica antiga.
Com que el VirtualBox és un programa que evoluciona ràpidament, és interessant
obtenir-ne una versió recent. Per aconseguir això i no sortir del sistema de
paquets de Debian, utilitzarem el dipòsit
https://backports.debian.org/[Debian Backports], que conté programari
actualitzat preparat per ésser instal·lat directament en una Debian estable.

- Editar el fitxer _/etc/apt/sources.list_ i afegir la línia:

----
deb http://ftp.debian.org/debian jessie-backports main contrib non-free
----

- Actualitzar la llista de paquets disponible amb:

----
# apt-get update
----

== Instal·lació del VirtualBox

Si no li diem el contrari, l'_apt-get_ instal·la els paquets de la versió
estable abans que de backports. Per indicar-li que una operació la volem
fer sobre un dipòsit en concret, utilitzem l'opció _-t_. Així, per instal·lar
el virtualbox ho farem amb:

----
# apt-get install -t jessie-backports virtualbox
----

== Compartició de la imatge per a les màquines virtuals

Per tal de no saturar la xarxa amb molts ordinadors descarregant la mateixa
imatge, utilitzarem un programari anomenat *zervit* que ens permet la
compartició ràpida de fitxers utilitzant el protocol HTTP, que és més ràpid
que l'ús de carpetes compartides.

El *zervit* actua com un servidor HTTP que comparteix automàticament el
directori on es troba el propi programa. No és útil, ni segur, per crear
servidors HTTP reals, però sí que és molt pràctic per traspassar fitxers
ràpidament a molts ordinadors de la mateixa xarxa.

El *zervit* es pot obtenir de la web http://zervit.sourceforge.net/.

Desgraciadament, hem de compilar-nos la versió per GNU/Linux (per Windows es
proporciona directament un executable).

Per compilar el programa seguirem els següents passos:

- Descarreguem el codi font del *zervit* de la seva web.
- Descomprimim el fitxer. Això ens crea el directori _zervit_.

Els següents passos estan explicats al fitxer _README_ que trobarem al lloc
on hem descomprimit:

- Instal·lar el paquet _scons_.
- Anar al directori _scripts_ i executar el programa _./mkiconfile.py_. Això
ens genera una sèrie d'icones necessàries per compilar el programa.
- Anar al directori _src_ i compilar el programa amb l'ordre _scons_. _scons_
automatitza el procés de compilació, així que sense fer res més hauria de
crear-se el fitxer executable _zervit_.

Per utilitzar-lo, només cal copiar el l'executable obtingut a la carpeta que
volguem compartir i executar-lo. Si volem utilitzar el port 80 per al servidor
HTTP (el port estàndard per aquest servei), hem d'executar el programa com
a _root_ (o utilitzant _sudo_), perquè es tracta d'un port reservat.

Els clients poden utilitzar el seu navegador web, posar l'adreça IP de
l'ordinador que comparteix el fitxer, i descarregar-se la imatge per a la
instal·lació.
